version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: ${FRONTEND_BUILD_STAGE:-dev}
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_APP_API_BASE_URL=http://backend:${BACKEND_PORT:-3001}/api
    depends_on:
      - backend
    command: npm run dev

  backend:
    container_name: backend
    build:
      context: ./backend
      target: ${BUILD_STAGE:-dev}
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${BACKEND_PORT:-3001}
    command: npm run dev